classdef prefix
    %ana.phys.unit.prefix       Unit prefixes.
    %
    %   Detailed explanation goes here

    properties (Constant)
        Letter = dictionary(...             % Units by letter.
                "E", 18,...
                "P", 15,...
                "T", 12,...
                "G",  9,...
                "M",  6,...
                "k",  3,...
                "d",  2,...
                "c",  1,...
                "m", -3,...
                "u", -6,...
                "µ", -6,...
                "n", -9,...
                "p",-12,...
                "f",-15,...
                "a",-18)
        Exponent = dictionary(...           % Units by exponent.
                 18,"E",...
                 15,"P",...
                 12,"T",...
                  9,"G",...
                  6,"M",...
                  3,"k",...
                  2,"d",...
                  1,"c",...
                 -3,"m",...
                 -6,"u",...
                 -9,"n",...
                -12,"p",...
                -15,"f",...
                -18,"a")
    end

    properties (Constant,Hidden)
        Config = ana.util.shared(struct(...  
            ))
    end

    methods
        function obj = prefix()
            %PREFIX Construct an instance of this class
            %   Detailed explanation goes here
        end
    end
end