classdef prefix
    %ana.phys.unit.prefix       Unit prefixes.
    %
    %   Detailed explanation goes here

    properties (Constant,Hidden)
        letter = dictionary(...             % Units by letter.
                "E", 18,...
                "P", 15,...
                "T", 12,...
                "G",  9,...
                "M",  6,...
                "k",  3,...
                "d",  2,...
                "c",  1,...
                "m", -3,...
                "u", -6,...
                "µ", -6,...
                "n", -9,...
                "p",-12,...
                "f",-15,...
                "a",-18)
        exponent = dictionary(...           % Units by exponent.
                 18,"E",...
                 15,"P",...
                 12,"T",...
                  9,"G",...
                  6,"M",...
                  3,"k",...
                  2,"d",...
                  1,"c",...
                  0,"",...
                 -3,"m",...
                 -6,"u",...
                 -9,"n",...
                -12,"p",...
                -15,"f",...
                -18,"a")
    end

    properties
        Exponent = 0
    end

    methods
        function varargout = set.Exponent(obj,value)
            arguments
                obj ana.phys.unit.prefix
                value
            end

            if isnumeric(value) && isscalar(value)
                try
                    ana.phys.unit.prefix.exponent(value);
                catch
                    FIXME
                end
                obj.Exponent = value;
                varargout{1} = obj; % Return the updated object
            else
                error('Exponent must be a numeric scalar.');
            end
        end

        function res = string(obj)
            arguments
                obj ana.phys.unit.prefix
            end

            res = obj.exponent(obj.Exponent);
        end
    end

    methods
        function obj = prefix()
            %PREFIX Construct an instance of this class
            %   Detailed explanation goes here
        end
    end
end